/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as BinsRouteImport } from './routes/bins'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiPredictionsRouteImport } from './routes/api/predictions'
import { Route as ApiOverviewRouteImport } from './routes/api/overview'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiBinsRouteImport } from './routes/api/bins'
import { Route as ApiAreasRouteImport } from './routes/api/areas'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const BinsRoute = BinsRouteImport.update({
  id: '/bins',
  path: '/bins',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsRoute = ApiPredictionsRouteImport.update({
  id: '/api/predictions',
  path: '/api/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverviewRoute = ApiOverviewRouteImport.update({
  id: '/api/overview',
  path: '/api/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinsRoute = ApiBinsRouteImport.update({
  id: '/api/bins',
  path: '/api/bins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAreasRoute = ApiAreasRouteImport.update({
  id: '/api/areas',
  path: '/api/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/bins': typeof BinsRoute
  '/camera': typeof CameraRoute
  '/devices': typeof DevicesRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/areas': typeof ApiAreasRoute
  '/api/bins': typeof ApiBinsRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/live': typeof ApiLiveRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/users': typeof ApiUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/bins': typeof BinsRoute
  '/camera': typeof CameraRoute
  '/devices': typeof DevicesRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/areas': typeof ApiAreasRoute
  '/api/bins': typeof ApiBinsRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/live': typeof ApiLiveRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/users': typeof ApiUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/bins': typeof BinsRoute
  '/camera': typeof CameraRoute
  '/devices': typeof DevicesRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/areas': typeof ApiAreasRoute
  '/api/bins': typeof ApiBinsRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/live': typeof ApiLiveRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/users': typeof ApiUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/alerts'
    | '/analytics'
    | '/bins'
    | '/camera'
    | '/devices'
    | '/live'
    | '/reports'
    | '/settings'
    | '/users'
    | '/api/alerts'
    | '/api/areas'
    | '/api/bins'
    | '/api/devices'
    | '/api/history'
    | '/api/live'
    | '/api/overview'
    | '/api/predictions'
    | '/api/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/alerts'
    | '/analytics'
    | '/bins'
    | '/camera'
    | '/devices'
    | '/live'
    | '/reports'
    | '/settings'
    | '/users'
    | '/api/alerts'
    | '/api/areas'
    | '/api/bins'
    | '/api/devices'
    | '/api/history'
    | '/api/live'
    | '/api/overview'
    | '/api/predictions'
    | '/api/users'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/alerts'
    | '/analytics'
    | '/bins'
    | '/camera'
    | '/devices'
    | '/live'
    | '/reports'
    | '/settings'
    | '/users'
    | '/api/alerts'
    | '/api/areas'
    | '/api/bins'
    | '/api/devices'
    | '/api/history'
    | '/api/live'
    | '/api/overview'
    | '/api/predictions'
    | '/api/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BinsRoute: typeof BinsRoute
  CameraRoute: typeof CameraRoute
  DevicesRoute: typeof DevicesRoute
  LiveRoute: typeof LiveRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiAreasRoute: typeof ApiAreasRoute
  ApiBinsRoute: typeof ApiBinsRoute
  ApiDevicesRoute: typeof ApiDevicesRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiOverviewRoute: typeof ApiOverviewRoute
  ApiPredictionsRoute: typeof ApiPredictionsRoute
  ApiUsersRoute: typeof ApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bins': {
      id: '/bins'
      path: '/bins'
      fullPath: '/bins'
      preLoaderRoute: typeof BinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions': {
      id: '/api/predictions'
      path: '/api/predictions'
      fullPath: '/api/predictions'
      preLoaderRoute: typeof ApiPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overview': {
      id: '/api/overview'
      path: '/api/overview'
      fullPath: '/api/overview'
      preLoaderRoute: typeof ApiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bins': {
      id: '/api/bins'
      path: '/api/bins'
      fullPath: '/api/bins'
      preLoaderRoute: typeof ApiBinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/areas': {
      id: '/api/areas'
      path: '/api/areas'
      fullPath: '/api/areas'
      preLoaderRoute: typeof ApiAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BinsRoute: BinsRoute,
  CameraRoute: CameraRoute,
  DevicesRoute: DevicesRoute,
  LiveRoute: LiveRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiAreasRoute: ApiAreasRoute,
  ApiBinsRoute: ApiBinsRoute,
  ApiDevicesRoute: ApiDevicesRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiOverviewRoute: ApiOverviewRoute,
  ApiPredictionsRoute: ApiPredictionsRoute,
  ApiUsersRoute: ApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
